### ISSUE TITLE
‘NoneType’ object has no attribute refresh_tokens

### ISSUE THREAD

**Issue by adamomg** [matejdro/login_control#1]
When I try to call the service with my user name, I get the error:

"Call-service API error. Error Message: ‘NoneType’ object has no attribute ‘refresh_tokens’ "

Running: Home Assistant 0.110.0

**Comment by matejdro** [comment]
How do you call the service?

**Comment by adamomg** [comment]
[https://imgur.com/1ZphIL8](https://imgur.com/1ZphIL8)

I also try to call it from node red with the same results

I've tried my own login and 2 other logins. Same error.

**Comment by matejdro** [comment]
I assume you enter login name of the user? You have to use user ID.

In HA, go to Configuration -> Persons -> Users -> Press on your user name. Window will open that will show your ID.

**Comment by matejdro** [comment]
Comment or reopen the issue if you still experience this with the provided instructions please.
